#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyhs100
Version  : 0.3.5.2
Release  : 24
URL      : https://files.pythonhosted.org/packages/00/a2/18543b5f4233dcb7616b73aa6ba48944bf36cf578d5860370c754bc619ed/pyHS100-0.3.5.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/00/a2/18543b5f4233dcb7616b73aa6ba48944bf36cf578d5860370c754bc619ed/pyHS100-0.3.5.2.tar.gz
Summary  : Interface for TPLink HS1xx plugs, HS2xx wall switches & LB1xx bulbs
Group    : Development/Tools
License  : GPL-3.0
Requires: pyhs100-bin = %{version}-%{release}
Requires: pyhs100-python = %{version}-%{release}
Requires: pyhs100-python3 = %{version}-%{release}
Requires: click
Requires: click-datetime
BuildRequires : buildreq-distutils3
BuildRequires : click
BuildRequires : click-datetime

%description
**This project is not updated anymore and should be considered abandoned.
The last released pypi version is in the `goodbye_release` branch.
Future developments will be done in asyncio-using fork, [python-kasa](https://github.com/python-kasa/python-kasa).**

%package bin
Summary: bin components for the pyhs100 package.
Group: Binaries

%description bin
bin components for the pyhs100 package.


%package python
Summary: python components for the pyhs100 package.
Group: Default
Requires: pyhs100-python3 = %{version}-%{release}

%description python
python components for the pyhs100 package.


%package python3
Summary: python3 components for the pyhs100 package.
Group: Default
Requires: python3-core
Provides: pypi(pyhs100)
Requires: pypi(click)
Requires: pypi(click_datetime)

%description python3
python3 components for the pyhs100 package.


%prep
%setup -q -n pyHS100-0.3.5.2
cd %{_builddir}/pyHS100-0.3.5.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1625015222
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyhs100

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
