#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyhs100
Version  : 0.3.4
Release  : 4
URL      : https://github.com/GadgetReactor/pyHS100/archive/0.3.4.tar.gz
Source0  : https://github.com/GadgetReactor/pyHS100/archive/0.3.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: pyhs100-bin = %{version}-%{release}
Requires: pyhs100-license = %{version}-%{release}
Requires: pyhs100-python = %{version}-%{release}
Requires: pyhs100-python3 = %{version}-%{release}
Requires: click
Requires: click-datetime
Requires: typing
BuildRequires : buildreq-distutils3
BuildRequires : click
BuildRequires : click-datetime
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : typing
BuildRequires : virtualenv

%description
# pyHS100
[![PyPI version](https://badge.fury.io/py/pyHS100.svg)](https://badge.fury.io/py/pyHS100)
[![Build Status](https://travis-ci.org/GadgetReactor/pyHS100.svg?branch=master)](https://travis-ci.org/GadgetReactor/pyHS100)
[![Coverage Status](https://coveralls.io/repos/github/GadgetReactor/pyHS100/badge.svg?branch=master)](https://coveralls.io/github/GadgetReactor/pyHS100?branch=master)
[![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com)

%package bin
Summary: bin components for the pyhs100 package.
Group: Binaries
Requires: pyhs100-license = %{version}-%{release}

%description bin
bin components for the pyhs100 package.


%package license
Summary: license components for the pyhs100 package.
Group: Default

%description license
license components for the pyhs100 package.


%package python
Summary: python components for the pyhs100 package.
Group: Default
Requires: pyhs100-python3 = %{version}-%{release}

%description python
python components for the pyhs100 package.


%package python3
Summary: python3 components for the pyhs100 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyhs100 package.


%prep
%setup -q -n pyHS100-0.3.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547736776
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyhs100
cp LICENSE %{buildroot}/usr/share/package-licenses/pyhs100/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyhs100

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyhs100/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
